// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CalcArg struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type Dosage struct {
	Strength *Strength `json:"strength"`
	Period   *Period   `json:"period"`
}

type Ingredient struct {
	PharmaceuticalForm *PharmaceuticalForm `json:"pharmaceuticalForm"`
	From               time.Time           `json:"from"`
	Substance          *Substance          `json:"substance"`
	Strength           *Strength           `json:"strength"`
}

type Medicine struct {
	Code       string      `json:"code"`
	Name       string      `json:"name"`
	Ingredient *Ingredient `json:"ingredient"`
}

type Period struct {
	Value float64 `json:"value"`
	Cron  string  `json:"cron"`
}

type PharmaceuticalForm struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type Posology struct {
	Note   string  `json:"note"`
	Dosage *Dosage `json:"dosage"`
}

type Strength struct {
	Unit  string  `json:"unit"`
	Value float64 `json:"value"`
}

type Substance struct {
	Code string `json:"code"`
	Name string `json:"name"`
}
