// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Filter struct {
	Name      *string `json:"name"`
	Substance *string `json:"substance"`
}

type Ingredient struct {
	PharmaceuticalForm *PharmaceuticalForm `json:"pharmaceuticalForm"`
	From               time.Time           `json:"from"`
	Substance          *Substance          `json:"substance"`
	Strength           *Strength           `json:"strength"`
}

type Medicine struct {
	Code          string      `json:"code"`
	Name          string      `json:"name"`
	Ingredient    *Ingredient `json:"ingredient"`
	PosologyNotes []string    `json:"posologyNotes"`
}

type PharmaceuticalForm struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type Strength struct {
	Unit  string  `json:"unit"`
	Value float64 `json:"value"`
}

type Substance struct {
	Code string `json:"code"`
	Name string `json:"name"`
}
