package parser

const (
	Vmp = "Vmp"
	TimeLayout           = "2006-01-02"
	Data                 = "Data"
	RealActualIngredient = "RealActualIngredient"
	Type                 = "Type"
	Amp                  = "Amp"
	AmpComponent         = "AmpComponent"
	Ampp         = "Ampp"
	Substance            = "Substance"
	Strength             = "Strength"
	OfficialName         = "OfficialName"
	PharmaceuticalForm = "PharmaceuticalForm"
	Nl = "Nl"
	Name = "Name"
	PosologyNote = "PosologyNote"
	AFrom                = "from"
	ATo                  = "to"
	AVmpCode             = "vmpCode"
	ACode = "code"
	AVmpComponentCode= "vmpComponentCode"
	AUnit = "unit"
)
